<?xml version="1.0"  encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE student [
 <!ELEMENT student (firstName,lastName,studentID,subjects)>
 <!ELEMENT subjects (subject*)>
 <!ELEMENT subject (code, creditPoint, mark, grade)>
 <!ELEMENT firstName (#PCDATA)>
 <!ELEMENT lastName (#PCDATA)>
 <!ELEMENT studentID (#PCDATA)>
 <!ELEMENT code (#PCDATA)>
 <!ELEMENT creditPoint (#PCDATA)>
 <!ELEMENT mark (#PCDATA)>
 <!ELEMENT grade (#PCDATA)>
]>
<student>
	<firstName>John</firstName>
	<lastName>Smith</lastName>
	<studentID>1231234</studentID>
	<subjects>
		<subject>
			<code>MATH101</code>
			<creditPoint>4</creditPoint>
			<mark>85</mark>
			<grade>A</grade>
		</subject>
		<subject>
			<code>ECON111</code>
			<creditPoint>5</creditPoint>
			<mark>70</mark>
			<grade>B</grade>
		</subject>
		<subject>
			<code>CS100</code>
			<creditPoint>5</creditPoint>
			<mark>80</mark>
			<grade>A</grade>
		</subject>
		<subject>
			<code>LAW121</code>
			<creditPoint>6</creditPoint>
			<mark>75</mark>
			<grade>B</grade>
		</subject>
	</subjects>
</student>